[syncers.mainnet]
electrum_server = "ssl://blockstream.info:700"
monero_daemon = "http://node.monerooutreach.org:18081"
monero_rpc_wallet = "http://localhost:18083"

[syncers.testnet]
electrum_server = "tcp://localhost:60001"
monero_daemon = "http://localhost:38081"
monero_rpc_wallet = "http://localhost:18083"

[syncers.local]
electrum_server = "tcp://localhost:50001"
monero_daemon = "http://localhost:18081"
monero_rpc_wallet = "http://localhost:18083"
