name: Build binaries

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**.rs'
      - 'build.rs'
      - 'Cargo.*'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**.rs'
      - 'build.rs'
      - 'Cargo.*'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  binaries:
    name: Build binaries
    strategy:
      matrix:
        rust: [
          1.59.0,
          stable
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y libsqlite3-dev libssl-dev libzmq3-dev pkg-config build-essential cmake

      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal

      - name: Rust cache
        uses: Swatinem/rust-cache@v2.6.2

      - name: Build farcaster daemon
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features
